services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      PATH: ${PATH_TO_BACK}
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PATH: ${PATH_TO_FRONT}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
